# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'Bitmall.xcworkspace'
use_frameworks!
inhibit_all_warnings!

target 'Bitmall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bitmall
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'SDWebImage'
  pod "SkeletonView"
  
  target 'BitmallData' do
    inherit! :search_paths
    project 'BitmallData/BitmallData'
    
    # Pods for testing
  end

  target 'BitmallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitmallUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    if ['PactConsumerSwift', 'Embassy'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
